In [9]:
import numpy as np
import pandas as pd

n_trials = nrows = 10000
n_dice = ncols = 2
rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)

In [10]:
rolls

array([[3, 1],
       [6, 3],
       [3, 3],
       ...,
       [1, 6],
       [1, 6],
       [2, 6]])

In [11]:
rolls_df = pd.DataFrame(rolls)

In [12]:
dubs = rolls_df.apply(lambda x: x[0] == x[1], axis = 1)

In [13]:
dubs.mean()

0.173

In [14]:
n_trials = nrows = 10000 
n_coins = ncols = 8
toss = np.random.choice([1,0], n_trials * n_coins).reshape(nrows, ncols)

In [15]:
toss

array([[1, 1, 1, ..., 1, 0, 1],
       [0, 1, 1, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [1, 0, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 1, 0],
       [1, 1, 0, ..., 0, 0, 0]])

In [17]:
trials = toss.sum(axis = 1)

In [18]:
(trials == 3).mean()

0.224

In [19]:
(trials > 3).mean()

0.6328

In [20]:
probabilities = [.75, .25]
billboard = np.random.choice(["web","data"], size = 10000, p = probabilities)
data = (billboard == "data").mean()
data * data 

0.061603240000000004

In [21]:
pop = np.random.normal(3, 1.5, size = [10000, 5])
pop[pop<0] = 0

In [22]:
pop

array([[3.3343289 , 1.31783712, 1.5423693 , 4.28976818, 4.913291  ],
       [3.91376638, 1.25346255, 4.9051417 , 2.60012266, 3.90481074],
       [3.79546333, 4.22187847, 4.95163216, 2.57023469, 2.84099974],
       ...,
       [3.01786933, 3.84933835, 1.42947985, 3.29574339, 0.8614715 ],
       [3.13861152, 1.95945484, 1.59548754, 2.34811998, 2.0623028 ],
       [3.18203159, 2.17397211, 0.39581032, 2.7965859 , 4.54975312]])

In [23]:
pop_df = pd.DataFrame(pop)

In [25]:
popeat = pop_df.apply(lambda x: x.sum(), axis = 1)

In [26]:
popeat

0       15.397595
1       16.577304
2       18.380208
3       14.220537
4       13.748474
          ...    
9995    15.575282
9996    15.629411
9997    12.453902
9998    11.103977
9999    13.098153
Length: 10000, dtype: float64

In [27]:
(popeat <= 16).mean()

0.6144

In [28]:
h_men = np.random.normal(178, 8, size = 10000)

In [29]:
h_men

array([183.70941791, 181.17307822, 186.96181278, ..., 176.8621433 ,
       181.93430025, 174.09912914])

In [30]:
h_wom = np.random.normal(170, 6, size = 10000)

In [31]:
tall = h_men - h_wom 

In [32]:
(tall < 0).mean()

0.2064

In [37]:
nrows = 10000
ncols = 450
cond_f = 1
cond_s = 0 
prob_failure = (1/250)

install = np.random.random((nrows, ncols))
((install < prob_failure).sum(axis = 1) == 0).mean()

0.1644

In [42]:
nrows = 10000
ncols = 2
food_truck = 1
no_food = 0
truck_prob = .7

data = np.random.random((nrows, ncols))
((data < truck_prob).sum(axis = 1) == 0).mean()

0.0861

In [43]:
1 - 0.0861

0.9139

In [47]:
days = range(0,365)
nrows = 100000
ncols = 22
classroom = np.random.choice(days, size = (nrows, ncols))

listofdays = [len(np.unique(classroom[n])) for n in range(0, nrows - 1) if len(np.unique(classroom[n])) > 1]

[22,
 21,
 20,
 22,
 21,
 21,
 22,
 22,
 22,
 21,
 22,
 20,
 22,
 22,
 21,
 22,
 22,
 22,
 20,
 22,
 22,
 21,
 21,
 22,
 22,
 21,
 22,
 22,
 22,
 21,
 22,
 22,
 21,
 21,
 22,
 20,
 22,
 21,
 22,
 22,
 22,
 21,
 19,
 22,
 22,
 21,
 19,
 21,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 21,
 22,
 21,
 20,
 21,
 22,
 22,
 22,
 21,
 21,
 22,
 21,
 21,
 22,
 21,
 21,
 22,
 22,
 22,
 21,
 20,
 22,
 21,
 22,
 21,
 21,
 20,
 22,
 21,
 20,
 21,
 21,
 21,
 22,
 22,
 21,
 22,
 22,
 21,
 21,
 21,
 21,
 19,
 22,
 21,
 22,
 21,
 21,
 22,
 22,
 19,
 21,
 21,
 22,
 22,
 22,
 21,
 21,
 22,
 21,
 22,
 22,
 22,
 21,
 21,
 22,
 19,
 22,
 22,
 21,
 22,
 21,
 22,
 21,
 22,
 22,
 22,
 22,
 22,
 21,
 21,
 21,
 22,
 22,
 21,
 22,
 21,
 21,
 21,
 22,
 22,
 22,
 21,
 21,
 22,
 21,
 19,
 22,
 22,
 22,
 22,
 21,
 22,
 22,
 22,
 22,
 22,
 22,
 20,
 22,
 21,
 22,
 20,
 22,
 21,
 22,
 21,
 22,
 21,
 21,
 20,
 21,
 22,
 22,
 22,
 20,
 21,
 22,
 22,
 22,
 22,
 22,
 20,
 19,
 22,
 21,
 22,
 20,
 22,
 21,
 22,
 21,
 22,
 22,
 19,
